// Math properties
let num = Math.E;
console.log(num);
num = Math.LN2;
console.log(num);
num = Math.LN10;
console.log(num);
num = Math.LOG2E;
console.log(num);
num = Math.LOG10E;
console.log(num);
num = Math.PI;
console.log(num);
num = Math.SQRT1_2;
console.log(num);
num = Math.SQRT2;
console.log(num);
//Math Methodes
num = Math.abs(12.213);
console.log(num);
num = Math.acos(0.3);
console.log(num);
num = Math.asin(0.3);
console.log(num);
num = Math.atan(0.3);
console.log(num);
num = Math.atan2(4,3);
console.log(num);
num = Math.ceil(0.6);
console.log(num);
num = Math.exp(2);
console.log(num);
num = Math.floor(1.3);
console.log(num);
num = Math.log(0.3);
console.log(num);
num = Math.max(2,32,3,5,74,43);
console.log(num);
num = Math.min(2,32,3,5,74,43);
console.log(num);
num = Math.pow(2,2);
console.log(num);
num = Math.random()*100;
console.log(num);
num = Math.round(2.2);
console.log(num);
num = Math.sin(45);
console.log(num);
num = Math.sqrt(4);
console.log(num);
num = Math.tan(1);
console.log(num);
num = Math.toSource();
console.log(num);